name: dev-vrabber-telegram-client

services:
  air:
    build:
      context: ../../.
      dockerfile: deploy/dev/air/Dockerfile
    env_file:
      - ".env"
    environment:
      - AIR_WORKDIR:/app
    volumes:
      - ../../.:/app
    networks:
      - dev-vrabber
    restart: on-failure

networks:
  dev-vrabber:
    external: true

#  postgres:
#    build:
#      context: ./postgres
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASS}
#      POSTGRES_DB: ${DB_NAME}
#    ports:
#      - ${DB_LOCAL_PORT}:5432
#    volumes:
#      - postgres-data-dev:/var/lib/postgresql/data
#    networks:
#      - vrabber-dev
#    deploy:
#      resources:
#        limits:
#          memory: 512M
#    healthcheck:
#      test: [ "CMD", "pg_isready" ]
#      interval: 5s
#      timeout: 10s
#      retries: 5
#    restart: unless-stopped
#
#  pgadmin:
#    build:
#      context: ./pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
#    ports:
#      - ${PGADMIN_LOCAL_PORT}:80
#    volumes:
#      - pgadmin-data-dev:/var/lib/pgadmin
#    networks:
#      - vrabber-dev
#    deploy:
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: 512M
#    healthcheck:
#      test: [ "CMD", "wget", "-O", "-", "http://localhost:80/misc/ping" ]
#      interval: 10s
#      timeout: 10s
#      retries: 5
#    restart: unless-stopped
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#  liquibase:
#    build:
#      context: ./liquibase
#    environment:
#      LIQUIBASE_COMMAND_USERNAME: ${DB_USER}
#      LIQUIBASE_COMMAND_PASSWORD: ${DB_PASS}
#      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
#      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.sql
#    volumes:
#      - ../migrations/changelog.sql:/liquibase/changelog.sql
#    networks:
#      - vrabber-dev
#    restart: on-failure
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#volumes:
#  postgres-data-dev:
#  pgadmin-data-dev:
#
