root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/client"
cmd = "go build -o ./tmp/client ./cmd/client"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
exclude_regex = ["_test.go"]
exclude_file = []
exclude_unchanged = false
follow_symlink = false
log = "air.log"
send_interrupt = false
stop_on_error = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
time = false

[misc]
clean_on_exit = true