name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on:
      group: default
    defaults:
      run:
        working-directory: /var/www/vrabber/telegram-client
    steps:
      - name: checkout main
        run: git switch main
      - name: pull changes
        run: git pull
      - name: update containers
        run: docker compose -f deploy/prod/docker-compose.yml {{.CLI_ARGS}}
